// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jemwazskuncpsnpqxsso.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImplbXdhenNrdW5jcHNucHF4c3NvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc2NjAwNjEsImV4cCI6MjA1MzIzNjA2MX0.G0hMc-f5X3MAIVoAn2CiRSvmOrlMAVaHBxcZdCiQPwU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);